### ISSUE TITLE
Investigar alternativas para interfaz de usuario

### ISSUE THREAD

**Issue by MiguelRodRic** [mrr0088/Gestor-de-Hemeroteca#4]
Los principales criterios (Obviando ser compatible con Python) serán:
-Flexibilidad para la visualización y manejo de pdf.
-Facilidad de distribución.
-Facilidad de cara al programador (Evitar dedicar excesivo tiempo a familiarizarse con la herramienta)

**Comment by MiguelRodRic** [comment]
Realizando mega tutorial de Flask.
Pros: Fácil de integrar html y JavaScript con Python
Contras: Continuo problema a la hora de ejecutar aplicaciones, no encontradas muchas librerías que integren visualización de pdf.

**Comment by MiguelRodRic** [comment]
Realizadas algunas pruebas  con PyQt. 
Pros: Interfaces fáciles de implementar, sin necesidad de html.
Contras: Aplicaciones de escritorio, no web
Enlaces de interés (relacionado con pdf):
https://pypi.python.org/pypi/python-poppler-qt4/
https://github.com/wbsoft/python-poppler-qt4
http://stackoverflow.com/questions/23389001/how-to-rendering-pdf-using-pdf-js-viewer-in-pyqt-webkit

**Comment by MiguelRodRic** [comment]
Herramientas para visualizar pdf en Jupyter:
http://stackoverflow.com/questions/19470099/view-pdf-image-in-an-ipython-notebook

**Comment by cgosorio** [comment]
Lo de mostrar en Jupyter el pdf con un IFrame es la solución que comentamos en la reunión del otro día. Una alternativa a la solución de convertir el .pdf a .png o .jpg, es convertir el .pdf a .svg usando inkscape (el formato .svg es directamente renderizable por el navegador y se puede incluir en un .html con la etiqueta img, la calidad es mejor que la del .png). 
```python
import subprocess
theFile = 'aPdfFile.pdf'
subprocess.call(['inkscape', '--without-gui', '--file='+theFile, '--export-plain-svg=output.svg'] 
```

**Comment by MiguelRodRic** [comment]
Reintentando el mega tutorial de flask. Persisten los mismos problemas al intentar ejecutar las aplicaciones. 
Si desde la terminal escribo "from flask import Flask" funciona correctamente, pero desde el script run.py, cuando llamo al script __init__.py no reconoce la línea "from flask import Flask".

**Comment by MiguelRodRic** [comment]
Finalizado Mega tutorial de Flask
