### ISSUE TITLE
Incluir el archivo requirements.txt

### ISSUE THREAD

**Issue by cgosorio** [mrr0088/Gestor-de-Hemeroteca#48]
Para facilitar la utilización de la aplicación es común incluir un archivo requiremens.txt en el directorio de la aplicación, una vez activado el entorno de desarrollo, utiliza
```
pip freeze > requirements.txt
```
para generarlo.

De este modo, luego para reproducir el entorno de ejecución instalando todas las dependencias necesarias es suficiente con usar
```
pip install -r requirements.txt
```

**Comment by MiguelRodRic** [comment]
Requirements.txt generado. En caso de instalar más librerías, se actualizará
