### ISSUE TITLE
Evitar el uso de literales que dependan del entorno local

### ISSUE THREAD

**Issue by cgosorio** [mrr0088/Gestor-de-Hemeroteca#51]
La inicialización
```python
ruta = '/home/miguel/Escritorio/Prototype_flask/pdf'
```
en vez de en views.py, estaría mejor en config.py, y tener configs distintos para desarrollo y producción.

Además, dado que es una subcarpeta dentro del proyecto, podrías obtener esa ruta a partir del path de ejecución de la aplicación. Echa un vistazo a este enlace http://www.faqs.org/docs/diveintopython/regression_path.html

En todo caso, en la aplicación final ese parámetro estaría bien que se pudiera fijar desde la interfaz de la aplicación.

**Comment by MiguelRodRic** [comment]
la variable path trasladada al fichero config y utilizado los métodos os.getcwd() y os.path.join para obtener la carpeta de los pdf
