### ISSUE TITLE
Evitar la creación de rutas a archivos mediante manipulación directa de cadenas

### ISSUE THREAD

**Issue by cgosorio** [mrr0088/Gestor-de-Hemeroteca#52]
En vez de cosas como:
```
path + '/' + filename
```
es mejor usar os.path.join, así te asegurar que no habrá problemas cuando la aplicación se ejecute en sistemas operativos que tengan distinta formas de separar directorios en una ruta.

**Comment by MiguelRodRic** [comment]
Sustuidas las concatenaciones de rutas por el metodo os.path.join
