### ISSUE TITLE
Valorar la utilización de algún boilerplate para la aplicación flask final

### ISSUE THREAD

**Issue by cgosorio** [mrr0088/Gestor-de-Hemeroteca#53]
Antes de ponerte con la aplicación flask final, considera echarle un vistazo a los siguientes enlaces, con distintas propuestas de estructuración de aplicaciones flask, te podrían facilitar las cosas (aunque no he visto ninguna con mongoDB):

- [cookiecutter-flask - A flask template with Bootstrap 3 and more for use with cookiecutter](https://github.com/sloria/cookiecutter-flask)
- [Fbone - a Flask template-bootstrap-boilerplate application](https://github.com/imwilsonxu/fbone)
- [flask-base - A simple Flask boilerplate app with SQLAlchemy, Redis, User Authentication, and more](https://github.com/hack4impact/flask-base)
- [flask-boilerplate - Boilerplate template for a Python Flask application](https://github.com/mjhea0/flask-boilerplate)
- [flask-bones - An example of a large scale Flask application using blueprints and extensions](https://github.com/cburmeister/flask-bones)
- [flask-empty - An empty project skeleton-boilerplate for flask projects](https://github.com/italomaia/flask-empty)
- [flask-skeleton - A skeleton for Flask applications](https://github.com/sean-/flask-skeleton)
- [Flask-Boilerplate - Fully fledged Flask boilerplate code](https://github.com/MaxHalford/Flask-Boilerplate)
- [flask-boilerplate - The basic Flask application structure that includes SQLAlchemy, Alembic, py.test and celery](https://github.com/sunscrapers/flask-boilerplate)
- [flask-bootstrap-apache-template](https://github.com/squadran2003/flask-bootstrap-apache-template)
- [flask-basic-registration - Starter app for managing users - login-logout and registration](https://github.com/mjhea0/flask-basic-registration)

**Comment by MiguelRodRic** [comment]
De acuerdo, gracias por las observaciones, voy a implementarlas y si tengo alguna duda mando correo u os comento en la siguiente reunión.


Un saludo

________________________________
De: cgosorio <notifications@github.com>
Enviado: viernes, 5 de mayo de 2017 9:54:15
Para: mrr0088/Python_DataClassification
Cc: Subscribed
Asunto: [mrr0088/Python_DataClassification] Valorar la utilización de algún boilerplate para la aplicación flask final (#53)


Antes de ponerte con la aplicación flask final, considera echarle un vistazo a los siguientes enlaces, con distintas propuestas de estructuración de aplicaciones flask, te podrían facilitar las cosas:

  *   cookiecutter-flask - A flask template with Bootstrap 3 and more for use with cookiecutter<https://github.com/sloria/cookiecutter-flask>
  *   Fbone - a Flask template-bootstrap-boilerplate application<https://github.com/imwilsonxu/fbone>
  *   flask-base - A simple Flask boilerplate app with SQLAlchemy, Redis, User Authentication, and more<https://github.com/hack4impact/flask-base>
  *   flask-boilerplate - Boilerplate template for a Python Flask application<https://github.com/mjhea0/flask-boilerplate>
  *   flask-bones - An example of a large scale Flask application using blueprints and extensions<https://github.com/cburmeister/flask-bones>
  *   flask-empty - An empty project skeleton-boilerplate for flask projects<https://github.com/italomaia/flask-empty>
  *   flask-skeleton - A skeleton for Flask applications<https://github.com/sean-/flask-skeleton>
  *   Flask-Boilerplate - Fully fledged Flask boilerplate code<https://github.com/MaxHalford/Flask-Boilerplate>
  *   flask-boilerplate - The basic Flask application structure that includes SQLAlchemy, Alembic, py.test and celery<https://github.com/sunscrapers/flask-boilerplate>
  *   flask-bootstrap-apache-template<https://github.com/squadran2003/flask-bootstrap-apache-template>
  *   flask-basic-registration - Starter app for managing users - login-logout and registration<https://github.com/mjhea0/flask-basic-registration>
