### ISSUE TITLE
Añadir un .gitignore al proyecto

### ISSUE THREAD

**Issue by cgosorio** [mrr0088/Gestor-de-Hemeroteca#88]
Sobre todo ahora que estás con la documentación, no tiene sentido que se sincronicen todos los archivos auxiliares que se generan con LaTeX. Añade a tu proyecto un archivo .gitignore con el siguiente contenido:
```

# LaTeX temporary files
*.aux
*.log
*.toc
*.lof
*.lot
*.out

# SyncTeX
*.synctex.gz

# BibTeX
*.bbl
*.blg

# Glosaries and indices
*.glo
*.idx
*.ilg
*.ind
*.ist
*.gls

# Others
*.acn
*.acr
*.alg
*.glg
*.maf
*.mtc
*.mtc1
```

**Comment by MiguelRodRic** [comment]
Creado gitignore tanto con este texto como con el que había en el issue #54, que también estaba pendiente
